baseURL = 'https://example.org/'
languageCode = "bg"
title = 'Царската идеология през Древността'
cleanDestinationDir = true
# If you installed the theme via Hugo Modules, you may remove this key
# theme = "hugo-neso"

mainSections = ["news", "publications"]

[minify]
  # Recommended: minify the generated output to improve page load time
  minifyOutput = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.imports]]
    path = "github.com/babeneso/hugo-neso" # must be this path
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

# Markdown
# --------------------------------

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      # Recommended: do not wrap <img> in <p> (the theme provides proper spacing)
      wrapStandAloneImageWithinParagraph = false

      [markup.goldmark.parser.attribute]
        # Required: enable attributes on block elements
        block = true

    [markup.goldmark.renderer]
      # Recommended: allow raw HTML in Markdown
      unsafe = true

  [markup.highlight]
    # Required: use CSS classes for code blocks so syntax highlighting works
    noClasses = false

  # Recommended: table of contents levels
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[outputs]  # The `outputs` table lives at the top level of TOML
  home = ["html", "rss", "json"]  # Ask Hugo to emit a JSON index

[menus]  # The `menus` table lives at the top level of TOML
  [[menus.main]]
    identifier = "news"   # unique id
    name       = "Новини"   # text shown in the menu
    pageRef    = "/news"  # your content section
    weight     = 10        # order (smaller appears earlier)


  [[menus.main]]
    # parent     = "about"
    identifier = "team"
    name       = "Екип"
    pageRef    = "/pages/team"   # your taxonomy: tags, categories, etc.
    weight     = 15

  [[menus.main]]
    identifier = "about_project"
    name       = "За проекта"
    pageRef    = "/pages/about-us"   # your taxonomy: tags, categories, etc.
    weight     = 17

  [[menus.main]]
    identifier = "publications"
    name       = "Публикации"
    pageRef    = "/publications"   # your taxonomy: tags, categories, etc.
    weight     = 20

  [[menus.main]]
    identifier = "gallery"
    name       = "Галерия"
    pageRef    = "/galleries"   # your taxonomy: tags, categories, etc.
    weight     = 22

  [[menus.main]]
    identifier = "tags"
    name       = "Категории"
    pageRef    = "/tags"   # your taxonomy: tags, categories, etc.
    weight     = 25
  # [[menus.main]]
  #   identifier = "categories"
  #   name       = "Categories"
  #   pageRef    = "/categories"  # your taxonomy: tags, categories, etc.
  #   weight     = 30
  [[menus.main]]
    identifier = "archives"
    # name       = "📂"
    name       = "Архив"
    pageRef    = "/archives"  # archives page
    weight     = 40
  [[menus.main]]
    identifier = "search"
    name       = "🔍"
    pageRef    = "/search"  # search page
    weight     = 50
  # [[menus.main]]
  #   identifier = "github"
  #   name       = "GitHub"
  #   url        = "https://github.com/babeneso"  # external link
  #   weight     = 60


[params]
  [params.neso]
    show_breadcrumbs = true
    time_format = "2 January, 2006"
    ext_link_indicator = true
    ext_link_new_window = true

    [params.neso.page]
      ext_link_indicator = true
      ext_link_new_window = true
      show_author = true
      hide_metadata = false

    [params.neso.home]
      display_mode = "profile"
      [params.neso.home.profile]
        # avatar_image = "img/profile-photo.jpg"
        [[params.neso.home.profile.link_btns]]
            label = "За проекта"
            url    = "/pages/about-us"
        [[params.neso.home.profile.link_btns]]
            label = "Екип"
            url   = "/pages/team"
      [params.neso.home.list]
        featured_entries_limit = 3

    [params.neso.social]
      [[params.neso.social.links]]
        name = "Facebook"
        url  = "https://www.facebook.com/profile.php?id=61574370416172"
      [[params.neso.social.links]]
        name = "Youtube"
        url  = "https://youtube.com"
      [[params.neso.social.links]]
        name = "Github"
        url  = "https://github.com/tarakanbg/royal-ideology-website"
      # [[params.neso.social.links]]
      #   name = "X"
      #   url  = "https://x.com/babeneso"

    [params.neso.branding]
      logo_text = "Moo"
      hide_logo_text = true
      logo_image = "img/logo.png"
      logo_image_dark = "img/logo_dark.png"
      logo_image_width = "220"
      logo_image_height = "90"
      og_image = "pages/about-us/project.jpg"

    [params.neso.search]
      input_placeholder = "Въведете ключова дума или фраза..."
